# Generated by Django 2.0.7 on 2018-07-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='reviewerData',
            new_name='reviewer_Email',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='ipAddress',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
