# Generated by Django 2.0.7 on 2018-07-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0003_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='User_Name',
        ),
    ]
