# Generated by Django 2.0.7 on 2018-07-26 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0005_reviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='Email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
