# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0006_login_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='Password',
        ),
    ]
